version: '3'
services:
  app:
    build:
      context: ./backend   # Chemin vers ton dossier backend
    ports:
      - "5000:5000"  # Exposer le port 5000 pour le backend
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=userdb

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
