name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Node.js pour tester ton backend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3. Installation des dépendances
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    # 4. Lancer les tests (optionnel si tu as des tests)
    - name: Run backend tests
      working-directory: ./backend
      run: npm test || echo "no tests yet"

    # 5. Login Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Build & Push Docker Image
    - name: Build & Push backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-management-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/user-management-backend:latest
